### ISSUE TITLE
Test Case: Verify Cross- Cutting Elements - Search Criteria List

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform-qa#100]
https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r

# Content Types Covered:
https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r

### Test Scenarios:

 - [ ] 1.Verify that the text "Hide Search Criteria" appears in the drop-down box when the dropdown is clicked.
- [ ] 2. Verify that Search Criteria dropdown contains expected search options for a) Basic search b) Advanced Search
- [ ]  3. Verify that 'Category' and 'Your Selection' headers are displayed in the Search Criteria box. 
- [ ] 4. Verify that the correct Category is displayed under the "Category" field and the correct selection is displayed under the "Your Selection" field.  

 
Depends on Issue #<number>

**Comment by kate-mashkina** [comment]
This issue was covered in multiple PRs
