### ISSUE TITLE
Test Case: Verify Cross-Cutting Elements - Delighters

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform-qa#101]
# Content Types Covered:
https://www.cancer.gov/about-cancer/treatment/clinical-trials/search

# Test Scenarios:
- [x] 1. Verify that the Live Help Delighter is displayed on Basic Search form, Advanced Search form, Search Results page and Trial Description page
- [x] 2. Verify that the "Which Trials are right for you" Delighter is displayed on Basic Search form, Advanced Search form, Search Results page and Trial Description page
- [x] 3. Verify that the "What are Cancer clinical Trials" Delighter is displayed on Basic and Advanced search form only.
- [x] 4. Verify that the redirect links are correct for three Delighters.
- [x] 5. Verify that the text is correctly displayed on the Delighters.
- [x] 6. verify that the icons are displayed correctly on all three Delighters.

Depends on Issue #2377[https://github.com/NCIOCPL/cgov-digital-platform/issues/2377]

Related

**Comment by SupriyaSaxena0605** [comment]
Assigning to @VictoriaSunNIH for review

**Comment by VictoriaSunNIH** [comment]
Looks good!

**Comment by kate-mashkina** [comment]
This issue had been tested from Basic Search, Search Results and Trial Details tests
