### ISSUE TITLE
Test Case: Verify Cross-Cutting Elements - Typeahead Feature

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform-qa#105]
# Content Types Covered:
* CTS basic: Cancer Type/Keyword field
* CTS advanced: Primary Cancer Type/Condition, Subtype, Stage, Side Effects/Biomarkers/Participant Attributes, Trial Investigators, Drug/Drug Family , Other Treatments , Lead Organization,
* Site Wide Search

# Test scenarios:
- [ ] 1.Verify that when user enters 3 letters, the auto suggest is displayed for the following fields:
 CTS Basic Search- Cancer Type/Keyword field 
 CTS Advanced Search-Primary Cancer Type/Condition, Subtype, Stage, Side Effects/Biomarkers/Participant Attributes, Drug/Drug Family , Other Treatments ,Trial Investigators, Lead Organization fields
- [ ] 3.Verify that the field allows single select options on Cancer Type/Keyword field on CTS Basic search
- [ ] 4.Verify that the field allows single select options on Primary Cancer Type/Condition, Trial Investigators and Lead Organization on CTS Advanced search
- [ ] 5.Verify that the field allows multi select options on Subtype, Stage, Side Effects/Biomarkers/Participant Attributes, Drug/Drug Family , Other Treatments on CTS Advanced Search

Depends on Issue [#2351](https://github.com/NCIOCPL/cgov-digital-platform/issues/2351)

**Comment by SupriyaSaxena0605** [comment]
Assigning to @VictoriaSunNIH for review

**Comment by kate-mashkina** [comment]
this issue is covered in both #95 and #92
