### ISSUE TITLE
Add an unconditional delay after each page load.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform-qa#125]
As a workaround for the DOM not being fully ready when the page is marked ready (e.g. JavaScript still running), add a configurable delay of `n` milliseconds between the time the page is loaded, and the time the page is made available to the test.  (e.g. `timeout.pagedelay=1000`)

The constructor for `PageObjectBase` looks like a promising location.

This is a _temporary_ measure and will need to be undone as part of #115.

**Comment by dragostiny** [comment]
The failure of tests was related to using an incorrect locator, not a synchronization issue
