### ISSUE TITLE
Test Case: Verify Browser Title

### ISSUE THREAD

**Issue by popkhadzeg** [NCIOCPL/cgov-digital-platform-qa#13]
## Pre-requisites
* Create YAML Content for all content type pages below
* Import YAML Content to test environment

## Content Types Covered:
- [x] Article -/about-cancer/coping/feelings
- [x] Article -/espanol/cancer/sobrellevar/sentimientos
- [x] Blog - /about-cancer/coping/feelings/relaxation/vitamin-d-supplement-cancer-prevention
- [x] Blog - /espanol/about-cancer/coping/feelings/relaxation/vitamina-d-complemento-cancer-prevencion
- [x] Press Release - /news-events/press-releases/2018/tmds-aml-risk-chemo
- [x] Press Release  - /espanol/noticias/comunicados-de-prensa/2018/tmds-aml-riesgo-quimio
- [x] Cancer Center  - /about-cancer/coping/feelings/relaxation/dukeci
- [x]  Bio - /about-cancer/coping/feelings/relaxation/loukissas-jennifer
- [x]  Blog Series - /news-events/cancer-currents-blog 
- [x]  Blog Series - /espanol/noticias/temas-y-relatos-blog
- [x]  Mini Landing Page - /about-nci/organization/ccct

## Test scenarios:
Browser Title:
1.	Navigate to page URL for each content type 
2.	Assert Browser Title is presented
3.	Assert that the Browser title text is non-empty 

Negative Tests:
1. Step1

**Comment by kate-mashkina** [comment]
Master already has PageTitle Tests
