### ISSUE TITLE
Test Case: Verify Lead Image

### ISSUE THREAD

**Issue by popkhadzeg** [NCIOCPL/cgov-digital-platform-qa#17]
## Pre-requisites
* Create YAML Content for all content type pages below
* Import YAML Content to test environment 

## Content Types Covered
- [ ] Article - #879
- [ ] Press Release - http://ncigovcdstg.prod.acquia-sites.com/node/281
- [ ] Blog -  #880  
- [ ] Cancer Center -http://ncigovcdstg.prod.acquia-sites.com/about-cancer/coping/feelings/relaxation/dfharvard
- [ ] Bio - http://ncigovcdstg.prod.acquia-sites.com/about-cancer/coping/feelings/relaxation/loukissas-jennifer

## Test scenarios:
1. Navigate to page URL for each content type
2. Assert Lead Image is presented on the page
3. Assert image has ALT text visible if available
4. Assert image Credit is visible  if available
5. Assert image caption is visible if available

Negative tests for Cancer center, Biography or any other content type having no lead image:
1. Assert Lead Image is NOT presented on the page (URL with no image)
2. Assert image ALT text is NOT visible if no ALT text is present (Url with Image/No ALT text)
3. Assert image Credit is NOT visible if no Credit is present (URL with Image/no Credit)
4. Assert image caption is NOT visible if no caption is present(URL with Image/No caption)

## Depends on Epic 
* #114

**Comment by SupriyaSaxena0605** [comment]
PR is approved and merged to master
