### ISSUE TITLE
Tests -Advanced CTS Age Section Functionality and Form

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform-qa#173]
from #95 
- [X] 19.Verify that the user is able to enter ages from 1 to 120 in the 'Age' input box.
- [X] 20.Verify that when user inputs Age and clicks Find Trials button, correct results are displayed.
- [X] 21.Verify that when user inputs Age which is < 1 or > 120 and clicks Find Trials button, following error message is displayed: "Please enter a number between 1 and 120."
- [X] 22.Verify when the user enters "1234" in the Age input box and clicks Find Trials button,  the following error message is displayed "Please enter a number between 1 and 120."
- [X] 23.Verify when the user enters "abcd" in the Age input box and clicks Find Trials button,  the following error message is displayed "Please enter a number between 1 and 120."

from #94 
15.Verify that the 'Age' Section is displayed.
16.Verify that the help link in the Age Section 'Age' links to https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/help#age
17. Verify the title of the Age section.
17.Verify that the helper text "Enter the age of the participant." appears for the 'Age' input box.
Depends on Issue #95
#94

**Comment by kate-mashkina** [comment]
PR is merged
