### ISSUE TITLE
Added Tests for Advanced Search Form KeywordsPhrases Section

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform-qa#176]
18.Verify that the 'Keywords/Phrases' section appears on the Advanced Search page (#94)

19. Verify the title of the Keywords/Phrases section. (#94 )

 19.Verify that the placeholder text "Examples: PSA, 'Paget disease" appears in the 'Keywords/Phrases' input box. (#94 )

 20.Verify that the 'Keywords/Phrases' help icon links to https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/help#keywords (#94 )

 21.Verify that the help text "Search by word or phrase (use quotation marks with phrases)." appears for the 'Keywords/Phrases' section. (#94)

24.Verify that when user inputs Keywords/Phrases such as "lymphoma" in the Keywords/Phrases input field and clicks Find Trials button, correct results are displayed. (#95 )
 25.Verify that when user inputs Keywords/Phrases such as "Hodgkin Lymphoma" (the term in double quotes) in the Keywords/Phrases input field and clicks Find Trials button, correct results are displayed. (#95 )
 26. Verify that when user inputs Keywords/Phrases such as "lymphoma" in the Keywords/Phrases input field and and hits enter, correct results are displayed. (#95)

Depends on Issue #<number>
#94 
#95

**Comment by kate-mashkina** [comment]
PR is merged
