### ISSUE TITLE
Test Case: Verify Syndicate

### ISSUE THREAD

**Issue by popkhadzeg** [NCIOCPL/cgov-digital-platform-qa#18]
## Pre-requisites
* Create YAML Content for all content type pages below
* Import YAML Content to test environment 

## Content Types Covered
- [ ] Article -  #881

## Test scenarios:
1. Navigate to page URL for Article content type
2. Assert Page Syndicate Text is presented
3. Assert Page Syndication link is active
4. Assert Syndication icon is presented

Negative Tests:
1. Navigate to other content type pages and verify Syndication Text and Link doesn't appear (URL's with other pages)

**Comment by KateMashkinaNIH** [comment]
this is moved to https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/issues/149
