### ISSUE TITLE
Verify the error message on No Results Page for invalid entries into different fields on Basic and Advanced CTS forms

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform-qa#184]
Verify the error message on No Results Page for invalid entries into different fields on Basic and Advanced CTS forms

The field for Basic CTS Form is:
Keyword Field

The fields for Advanced CTS Form are:
City
Hospital
Keyword Phrases 
Trial Investigators - Waiting on PR approval (#180 )
Lead Organizations - waiting on PR approval (#186 )
Trial ID - done

Note : Also, we need to refactor all tests that are testing 'rl' only as the query param for testing the query params in Search Results Page.

**Comment by KateMashkinaNIH** [comment]
this is a part of App acceptance tests , see https://github.com/NCIOCPL/clinical-trials-search-app/tree/develop/cypress/integration
