### ISSUE TITLE
Test Case: Tests for Advanced Search Form Drug Treatment Section

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform-qa#189]
# Test URL: 
https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/advanced
# Tests Covered:
- [x] 38.Verify that the input box 'Drug/Treatment' is displayed.
 - [x] 43.Verify that the placeholder text "Start typing to select drugs and/or drug families" appears in the input box 'Drug/Drug Family'.
 - [x] 46.Verify that the placeholder text "Start typing to select other treatments" displayed in the input box 'Other Treatments'.
- [x] 50. Verify that when user selects an option from the autocomplete for the 'Drug/Drug Family' and clicks Find Trials button, correct results are displayed.
- [x] 51.Verify that when user selects multiple options from the 'Drug/Drug Family' and clicks Find Trials button, correct results are displayed.
- [x] 52.Verify that the helper text 'Please enter 3 or more characters' appears on clicking the the 'Other Treatments' input box within the Drug/Treatment input box.
- [x] 53. Verify that when user selects an option from the autocomplete for the  'Other Treatments' input box and clicks Find Trials button, correct results are displayed.
- [x] 54.Verify that when user selects multiple options from the autocomplete for the 'Other Treatments' and clicks Find Trials button, correct results are displayed.
- [x] Verify that when user selects Drug value and Other Treatment value and click the Clear form button, the Advanced Search form is refreshed and populated field are cleared.
- [x] Verify that when user selects an option from the autocomplete for the 'Drug/Drug Family' and hits Enter key, correct results are displayed.
-[x] Verify that when user selects an option from the autocomplete for the  'Other Treatments' input box and hits Enter key, correct results are displayed.

Depends on Issue #94 #95

**Comment by kate-mashkina** [comment]
PR #192 is merged
