### ISSUE TITLE
Test Case: Tests for Advanced Search Form Location Section

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform-qa#193]
# Test URL: 
https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/advanced
# Tests Covered:
- [x] Verify that Location section is displayed
- [x] 26.Verify that on switching the toggle to "Yes" for the Location input box, the following radio buttons appear:
Search All Locations
ZIP Code
Country, State, City
- [x] 27.Verify that on selecting the ZIP Code radio button, the following input box and the drop-down appears:
U.S. ZIP Code (input box)
Radius (drop-down)
- [x] 29.Verify that when user inputs U.S. ZIP Code as '99999' and '00000' and clicks Find Trials button, following error message is displayed: "Please enter a valid 5 digit U.S. zip code"
- [x] 30.Verify when the user enters "abcd" in the U.S. ZIP Code input box and clicks Find Trials button,  the following error message is displayed "Please enter a valid 5 digit U.S. zip code.."
- [x] 31.Verify when the user enters "1234" in the U.S. ZIP Code input box and clicks Find Trials button,  the following error message is displayed "Please enter a valid 5 digit U.S. zip code.."
- [x] Verify that when user enter zip code and select the radius from the 'Radius' drop-down and click Find Trials button, correct results are displayed.
- [x] 32.Verify that the user is able to select the radius from the 'Radius' drop-down.
- [x] 33. Verify that on selecting 'Country, State, City' radio button, the following are displayed:
Country - which should appear as drop-down
State-which should appear as a multi-select box
City-which should display as input box
- [x] 34.Verify that in the Country drop-down, "United States" appears by default
- [x] 35.Verify that the user is able to select values from the Country drop-down.
- [x] 36.Verify that the user is able to enter multiple state in the 'State' multi-select input box
- [x] 37.Verify that when the user types a letter (for example 'p') the State starting with the letter 'P' shows up in the auto-suggest list
- [x] 39. Verify that the user is able to enter the name of a city in the 'City' input box.
- [x] 40.Verify that on selecting Hospitals/Institutions radio button an auto complete input box is displayed
- [x] 42.Verify that the text "Please enter 3 or more characters" appears on clicking the 'Hospitals/Institutions' autocomplete input box
- [x] 43.Verify that the user is able to select the radio button 'At NIH (only show trials at the NIH Clinical Center in Bethesda, MD)

Depends on Issue #<95>

**Comment by KateMashkinaNIH** [comment]
done here https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/tree/master/cypress/integration/CTS
