### ISSUE TITLE
Test Case: Tests for Advanced Search Form Cancer Type/Condition

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform-qa#199]
# Test URL: 
https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/advanced
# Tests Covered:

- [x] Verify that the Cancer Type/ Condition section is displayed.
- [x] Verify that the dropdown button "All" appears in the Primary Cancer Type/Condition input box.
- [x] Verify that when user inputs a value to the Primary Cancer Type/Condition and clicks Find Trials button, correct results are displayed.
- [x] Verify when user clicks on the Primary Cancer Type/Condition input box, a box appears with the placeholder text "Start typing to narrow options below".
- [x] Verify that when user inputs a value (for example, Acute Lymphoblastic Leukemia (ALL)) to the Primary Cancer Type/Condition field the following input boxes are displayed:
Subtype
Stage 
Side Effects/Biomarkers/Participant Attributes
- [ ]  Verify that the placeholder text 'Start typing to select a subtype' appears for the Subtype input box.
- [x] Verify when user enters "we" to the Subtype input box , the helper text "No available options based on your previous selections" appears for the Subtype input box.
- [x] Verify that when user inputs a value (for example, Acute Lymphoblastic Leukemia (ALL)) to the Primary Cancer Type/Condition and inputs a value (for example, B Acute Lymphoblastic Leukemia) to the Subtype  and clicks Find Trials button, correct results are displayed.
- [x] Verify that when user inputs a value (for example, Acute Lymphoblastic Leukemia (ALL)) to the Primary Cancer Type/Condition and inputs a value (for example, B Acute Lymphoblastic Leukemia) to the Subtype  and hits 'ENTER' from the keyboard correct results are displayed.
- [ ] Verify that the placeholder text "Start typing to select a stage" appears for the Stage input box.
- [x] Verify when user enters "we" the helper text "No available options based on your previous selections" appears for the Stage input box.
- [x] Verify that when user inputs a value (for example, Acute Lymphoblastic Leukemia (ALL)) to the Primary Cancer Type/Condition and inputs Stage (for example,Recurrent Acute Lymphoblastic Leukemia)  and clicks Find Trials button, correct results are displayed. 
- [x] Verify that when user inputs a value (for example, Acute Lymphoblastic Leukemia (ALL)) to the Primary Cancer Type/Condition and inputs Stage (for example,Recurrent Acute Lymphoblastic Leukemia)  and hits 'ENTER' from the keyboard correct results are displayed.
- [ ] Verify that the placeholder text 'Examples: Nausea, BRCA1' appears for the Side Effects/Biomarkers/Participant Attributes input box.
- [x] Verify when user enters "we" the helper text "No available options based on your previous selections" appears for the Side Effects/Biomarkers/Participant Attributes input box.
- [x] Verify that when inputs a value (for example, Acute Lymphoblastic Leukemia (ALL)) to the Primary Cancer Type/Condition and inputs a value (for example, Acute Leukemia in Remission) in the Side Effects/Biomarkers/Participant Attributes and clicks Find Trials button, correct results are displayed.
- [x] Verify that when user inputs a value (for example, Acute Lymphoblastic Leukemia (ALL)) to the Primary Cancer Type/Condition and inputs a value (for example, Acute Leukemia in Remission) in the Side Effects/Biomarkers/Participant Attributes and  and hits 'ENTER' from the keyboard correct results are displayed.
- [x] Verify that when the user inputs a value to the Primary Cancer Type/Condition, Subtype, Stage, Side Effects/Biomarkers/Participant Attributes and clicks Find Trials button, correct results are displayed.
- [x] Verify that when the user inputs a value to the Primary Cancer Type/Condition, Subtype, Stage, Side Effects/Biomarkers/Participant Attributes and hits 'ENTER' from the keyboard correct results are displayed.
- [x] Verify that when the user inputs a value to the Primary Cancer Type/Condition, Subtype and Side Effects/Biomarkers/Participant Attributes and clicks Find Trials button, correct results are displayed.
- [x] Verify that when the user inputs a value to the Primary Cancer Type/Condition, Subtype and Side Effects/Biomarkers/Participant Attributes and  hits 'ENTER' from the keyboard correct results are displayed.
- [x] Verify that when the user inputs Primary Cancer Type/Condition, Stage and Side Effects/Biomarkers/Participant Attributes and clicks Find Trials button, correct results are displayed.
- [x]  Verify that when the user inputs Primary Cancer Type/Condition, Stage and Side Effects/Biomarkers/Participant Attributes hits 'ENTER' from the keyboard correct results are displayed.
- [x] Verify that when user does NOT enter any input to Primary Cancer Type/Condition, Subtype, Stage and Side Effects/Biomarkers/Participant Attributes and clicks Find Trials button, all results are displayed.

Depends on (#94 ) and (#95 )

**Comment by kate-mashkina** [comment]
Deleted steps that were verifying the content
Approved

**Comment by KateMashkinaNIH** [comment]
this is done here https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/tree/master/cypress/integration/CTS
