### ISSUE TITLE
Changed ParsedURL to store query parameters in a list instead of map.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform-qa#202]
The queryPairs field should not be a map as it’s valid for a parameter name to appear multiple times (e.g. [/search/r/?loc=0&rl=2&tt=treatment&tt=supportive_care&tt=diagnostic](https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r?loc=0&rl=2&tt=treatment&tt=supportive_care&tt=diagnostic)). 

The current implementation doesn't account for these collisions and will either have errors, or fail in more subtle ways.  For purposes of our test automation, let’s just use a list of name/value pairs and have `getQueryParam()` do whatever searching it needs to do.

**Comment by kate-mashkina** [comment]
PR is merged
