### ISSUE TITLE
Test Case: Verify Google Analytics: Callout Boxes

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform-qa#210]
# Pre-requisites
* pre-condition

# Content Types Covered:
* Type 1
* Type 2
* Type 3

# Steps:
1. Step
2. Step
3. Step

Depends on Issue #<number>

**Comment by kate-mashkina** [comment]
analytic testing is moved to the following repository https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests
