### ISSUE TITLE
Test Case: Verify Pretty URL

### ISSUE THREAD

**Issue by popkhadzeg** [NCIOCPL/cgov-digital-platform-qa#40]
# Pre-requisites
* All content types with Pretty Url 

# Content Types Covered:
* All Content Types, home pages and list pages

# Steps:
1. Navigate to given URL
2. Assert the current page URL contains `pretty-url`
3. Assert page displays with no errors

Depends on Issue #<number>

#Requirement Reference
https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Pretty-URL

**Comment by KateMashkinaNIH** [comment]
this is not a valid test case 
we have 
1) redirect to purl
2) all pages are being navigated to using their purls
