### ISSUE TITLE
Test Case: Verify Feature Card on Pages with Feature card

### ISSUE THREAD

**Issue by popkhadzeg** [NCIOCPL/cgov-digital-platform-qa#43]
## Pre-requisites
* Create YAML Content for all content type pages below
* Import YAML Content to test environment 

## Content Types Covered
- [x] Mini Landing Page
- [x] Home & Landing Page
- [x] Cancer Type Home Pages
- [x] Blog Landing Page (Series page)

## Test scenarios:
1. Assert Feature card is displayed on the page if available
2. Check the Card title [#36](https://github.com/NCIOCPL/cgov-digital-platform-qa/issues/36)
3. Check the Card Description [#39](https://github.com/NCIOCPL/cgov-digital-platform-qa/issues/39)
4. Assert Promotional Image is presented on the page
5. Assert image has ALT text visible if available
6. Verify the Image source is not empty
7. Verify the Image source is not null
8. Verify the Image source url starts with "/"

Negative tests for PDQ Cancer Info Summary, PDQ Drug Info Summary and other content types having no Promotional image:
1. Assert Promotional Image is displayed on a feature card if lead image is not present. (URL with no lead image)
2. Assert that the correct crop of Lead Image is displayed on a feature card if Promotional image is not present.
3. Assert image ALT text is NOT visible if no ALT text is present (Url with Image/No ALT text)

Depends on Issue #<number>
##Requirement Reference
https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Promotional-Image

**Comment by SupriyaSaxena0605** [comment]
PR#85 awaiting approval from Blair

**Comment by kate-mashkina** [comment]
PR#85 resolving this issue has been merged
