### ISSUE TITLE
Test Case: Verify Cross-Cutting Elements: Verify the right metadata is being pulled for page options

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform-qa#44]
# Pre-requisites

* pre-condition
Page options requires metatags to be done for them to work

# Content Types Covered:
All

# Steps:
1. Verify that the system shall have the following social media metadata:
- og:title
- og:description
- og:type
- og:image
- og:url
- og:sitename
- twitter:card
2. Verify that the system shall map the og:title metadata to the "Short Title" field on content items

Reference: https://github.com/NCIOCPL/cgov-digital-platform/issues/1551
Depends on Issue #https://github.com/NCIOCPL/cgov-digital-platform/issues/197
                              #https://github.com/NCIOCPL/cgov-digital-platform/pull/1509

**Comment by kate-mashkina** [comment]
this is done in https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/blob/master/cypress/integration/MetaData/MetaDataTests.feature
