### ISSUE TITLE
Test Case: Verify Search Engine Restrictions

### ISSUE THREAD

**Issue by popkhadzeg** [NCIOCPL/cgov-digital-platform-qa#46]
## Pre-requisites
* pre-condition

## Content Types Covered:
Article
Press Release
Cancer Center
Biography
Event
Mini Landing Page
Home & Landing Page
Cancer Type Home Pages
Blog Landing Page (Blog Series)
Blog Posts
Infographic
Cancer Reserach List
Video
File (???)

## Steps:
1. Verify that meta name="robots" content="index" appears in the source code if the Include in search is selected
2.Verify that meta name="robots" content="noindex" appears in the source code if the Exclude from search is selected

Depends on Issue #<number>
## Requirement Reference
https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Search-Engine-Restrictions

**Comment by blairlearn** [comment]
Reopening - test data only covers the English versions of article, biography and blog post.

**Comment by alinai** [comment]
Updated the data provider  searchenginerestrictions_data.xlsx  with more content types.

**Comment by kate-mashkina** [comment]
closed by #75
