### ISSUE TITLE
Test Case: Verify Cross-Cutting Elements - Breadcrumbs

### ISSUE THREAD

**Issue by popkhadzeg** [NCIOCPL/cgov-digital-platform-qa#50]
# Pre-requisites
* pre-condition

# Content Types Covered:
All pages except Home and Landing Pages

# Steps:
* [x] The system shall display breadcrumbs on desktop and tablet breakpoints
* [x] The system shall not display breadcrumbs on the homepage or landing pages.
* [x] The system shall not display breadcrumbs on mobile breakpoints
* [x] The system shall display each breadcrumb in the path as a link
* [x] The system shall not display the breadcrumb of the user's current page location

**Comment by SupriyaSaxena0605** [comment]
PR#110 awaiting approval from Blair
