### ISSUE TITLE
Test Case: Verify Cross-Cutting Elements - Back To Top

### ISSUE THREAD

**Issue by popkhadzeg** [NCIOCPL/cgov-digital-platform-qa#51]
# Pre-requisites
* pre-condition

# Content Types Covered:
* The   system shall display a "Back to Top" option across all pages on the   desktop site

# Steps:
1. The   system shall not display the "Back To Top" option when the user is viewing the site in mobile size
2. The   system shall allow the Back to Top option to appear when user has scrolled to 600 px down the screen
3. The   system shall not display the Back to Top option when user is at the top of   the screen on desktop

Depends on Issue #<number>

**Comment by KateMashkinaNIH** [comment]
this is now a part of https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/issues/150
