### ISSUE TITLE
Look for "Español" instead of "Spanish" in the language toggle.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform-qa#54]
Commit bfd3a90 modifies the language toggle test data (`test-data/languagetoggle-data.xlsx`) to expect the word "Spanish" in the language toggle instead of "Español".

This is because the language toggle currently displays the incorrect text. **After** NCIOCPL/cgov-digital-platform#1541 is resolved, the test data should be switched back.

**Comment by SupriyaSaxena0605** [comment]
This is fixed and implemented. Closed by #129
