### ISSUE TITLE
YAML Content Request for Spanish Article with Lead Image

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform-qa#57]
Content Type: Article in Spanish with lead image with credit, caption, alt text
Live Site URL: https://www.cancer.gov/espanol/cancer/tratamiento/efectos-secundarios

**Comment by popkhadzeg** [comment]
Completed on local devbox and needs to be pushed to dev:
http://www.devbox/espanol/efectos-secundarios
