### ISSUE TITLE
YAML Content Request for Press Release with lead image

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform-qa#58]
Content Type: Press Release in English with lead image with credit, caption, alt text
Live Site URL: https://www.cancer.gov/news-events/press-releases/2018/melanoma-immunotherapy-predictor

**Comment by popkhadzeg** [comment]
Completed on local devbox and needs to be pushed to dev:
http://www.devbox/news-events/press-releases/2018/cll-ibrutinib-trial
