### ISSUE TITLE
YAML Content Request for Press release in Spanish with Lead image

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform-qa#59]
Content Type: Press Release in Spanish with lead image with credit, caption, alt text
Live Site URL: https://www.cancer.gov/espanol/noticias/comunicados-de-prensa/2018/llc-ibrutinib-estudio

**Comment by popkhadzeg** [comment]
Completed on local devbox and needs to be pushed to dev:
http://www.devbox/espanol/noticias/comunicados-de-prensa/2018/llc-ibrutinib-estudio
