### ISSUE TITLE
YAML Content Request Blog post with Lead Image

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform-qa#60]
Content Type: Blog post with Lead Image with credit, caption, alt text
Live Site URL: https://www.cancer.gov/news-events/cancer-currents-blog/2019/transition-lowy-nci-acting-director

**Comment by popkhadzeg** [comment]
Completed on local devbox and needs to be pushed to dev:
http://www.devbox/news-events/cancer-currents-blog/2019/transition-lowy-nci-acting-director
