### ISSUE TITLE
Need capability to test HTTP status codes

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform-qa#62]
Selenium does not expose functionality to examine HTTP status codes (or much of anything else that low level). This prevents us from creating tests to verify redirects, HTTP headers, etc.

Proposed solution:

Create an `HttpProtocolPage` class, similar to `PageObjectBase` to request a URL and expose the desired information.

**Comment by kate-mashkina** [comment]
@blairlearn 
I have a solution ready for testing the HTTP requests.

The following clarification required:

1. What content types(URL) will need to be included in the test data
2. What specific headers to be validated? (e.g. URL "/about-cancer/coping/feelings" returns 29 headers)

_P.S. The test suite will include checking the status code and match the headers._
