### ISSUE TITLE
Add test scenarios for "accessible text version" field.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform-qa#67]
Images and infographics have an "Accessible Text Version" field containing a plain-text description of the image's content. When this field is set, and the image is used as an article's Lead Image, the image is rendered with a `longdesc` attribute which retrieves the text. For infographics, this attribute is always rendered when the field is set.

**Comment by KateMashkinaNIH** [comment]
this is taken care of in https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/issues/147 and https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/issues/146
