### ISSUE TITLE
Test Case: Verify On This page section 

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform-qa#73]
# Pre-requisites
* YAML content creation 

# Content Types Covered:
* Article
* PDQ Cancer Info Summary

# Steps:
1. Verify that On this page section is displayed on the page if available
2. Verify "On This Page" section header is in correct translation
3. Verify "On This Page" anchor links are not broken/blank
4. Verify Body headers and "On This Page" anchor links match
5. Verify "On this page" section is not displayed if not available on content types other than Article and PDQ cancer info Summary.
5. Verify that the anchor links are displayed as accordion on mobile breakpoint.
 

Depends on Issue #<number>

#Requirement Reference:
https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Article

**Comment by KateMashkinaNIH** [comment]
this is moved to https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/issues/148
