### ISSUE TITLE
Search Engine Restriction tests give a false failure.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform-qa#80]
`SearchEngineRestrictions_Test:: verifyExcludeFromSearchIsSelected` give a false test failure because it is testing pages which do not have search engine restrictions.

**Comment by alinai** [comment]
A ticket ( https://github.com/NCIOCPL/cgov-digital-platform-qa/issues/68 ) has already been entered for YAML content to test for SearchEngineRestrictions_Test:: verifyExcludeFromSearchIsSelected.
