### ISSUE TITLE
Create test cases to test page metadata

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform-qa#89]
We have now had 2 releases in which odd ball metadata issues are still plaguing us. Please create test cases that test all of the metadata requirements. This includes title, meta description, og metatags, twitter metatags, etc. This should test every type of node, both in English and Spanish.

**Comment by bryanpizzillo** [comment]
@popkhadzeg I trust you will turn this into the necessary test cases.

@blairlearn @VictoriaSunNIH @sarinapadilla FYI

**Comment by kate-mashkina** [comment]
PR containing tests is merged into Master
