### ISSUE TITLE
Test Case:  All SEO page metadata testcases

### ISSUE THREAD

**Issue by popkhadzeg** [NCIOCPL/cgov-digital-platform-qa#90]
This master test case is the list of combined requirements and test steps for SEO metadata.

### All Metadata Scenarios:

- [x] Search Engine Restrictions #46 
search engine restrictions (if exclude from search is selected, this should output noindex nofollow.  e.g. `<META` NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">)
1. Verify that meta name="robots" content="index" appears in the source code if the Include in search is selected
2.Verify that meta name="robots" content="noindex" appears in the source code if the Exclude from search is selected
_______
- [x] browser title
we need to append the Site Name to the browser title with a dash (e.g. National Cancer Institute for cancer.gov). Display would be "Browser Title - Site Name"
1. Navigate to given URL for each content type
2. Verify that `<meta name="title" content=[Browser title]` appears in the source code 
3. Verify browser title is appended with the Site name (e.g. National Cancer Institute)
4. Verify both English and Spanish content URLs
_______
- [x] metadescription
1. Navigate to given URL for each content type
2. Verify that `<meta name="description" content=[Meta-Description] ` appears in the source code
3. Verify both English and Spanish content URLs

_______

- [x] og:title
Map to [Browser title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#browser-title) field

1. Navigate to given URL for each content type
2. Verify that `<meta property="og:title" content=[Browser title]` appears in the source code
3. Verify both English and Spanish content URLs
Referenced ticket #13 
_______
- [x] og:description
Map to [Meta-Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#meta-description)
1. Navigate to given URL for each content type
2. Verify that `<meta property="og:description" content=[Meta-Description] ` appears in the source code
3. Verify both English and Spanish content URLs
_______

- [x] og:type
The system shall set a default value of "website" to og:type
The system shall allow the default value to be overridden by the page template
1. Navigate to given URL for each content type
2. Verify that `<meta property="og:type" content="Website" ` appears in the source code
3. Verify both English and Spanish content URLs
_______

- [x] og:url
Based on meta property=og:url
Use the Canonical URL (link rel="canonical") when the OpenGraph URL does not exist
1. Navigate to given URL for each content type
2. Verify that `<meta property=og:url" content=[URL] ` appears in the source code
3. Verify both English and Spanish content URLs
_______

- [x] og:sitename
Based on the site the user is on (need to figure out how this works for non www microsites).  The site names should be:
      * Cancer.gov: National Cancer Institute
      * DCEG: Division of Cancer Epidemiology & Genetics - National Cancer Institute
1. Navigate to given URL for each content type
2. Verify that `<meta property="og:site_name" content=[Site Name] ` appears in the source code
3. Verify both English and Spanish content URLs
_______

- [x] twitter:card
The system shall set a default value of "summary" to twitter:card
The system shall allow Twitter to use the OpenGraph metadata for similar Twitter metadata fields
1. Navigate to given URL for each content type
2. Verify that `<meta name="twitter:card" content="summary"` appears in the source code
3. Verify both English and Spanish content URLs

_______

- [x] Href Lang
link rel="alternate" hreflang="es" href="http://es.example.com/foo" to the head block of the HTML page. This tells search engines how to find the content.
As a user, I would like to correctly identify my content for DTM and Internal NCI Search.
1. Navigate to given URL for each content type
2. Verify that `<link rel="alternate" hreflang="en"`, `<link rel="alternate" hreflang="es"`appears in the source code
3. Verify both English and Spanish content URLs
_______

### dcTerms

- [x] dcterms.type
dcterms.type (NOTE: we need to make sure that qualtrics is using these new tags to determine where surveys appear, and not "data-cde-contenttype" as its target)
1. Navigate to given URL for each content type
2. Verify that  `<meta name="dcterms.type" content="cgvArticle" ` appears in the source code
3. Verify both English and Spanish content URLs
_______

- [x] dcterms.subject

1. Navigate to given URL for each content type
2. Verify that  `<meta name="dcterms.subject" content="About Cancer" ` appears in the source code
3. Verify both English and Spanish content URLs
_______

- [x] dcterms.isReferencedBy

1. Navigate to given URL for each content type
2. Verify that  `meta name="dcterms.isReferencedBy" content="event1" ` appears in the source code
3. Verify both English and Spanish content URLs
_______

- [x] dcterms.isPartOf

1. Navigate to given URL for each content type
2. Verify that  `meta name="dcterms.isPartOf" content="Coping"  ` appears in the source code
3. Verify both English and Spanish content URLs
_______

- [x] dcterms.coverage

1. Navigate to given URL for each content type
2. Verify that  `meta name="dcterms.coverage" content="nciglobal,ncienterprise"` appears in the source code
3. Verify both English and Spanish content URLs
_______
- [x] dcterms.issued

1. Navigate to given URL for each content type
2. Verify that  `meta name="dcterms.issued" content="08/20/2018 - 08:00"` appears in the source code
3. Verify both English and Spanish content URLs
_______

**Comment by dragostiny** [comment]
All the tests PR had been approved

**Comment by kate-mashkina** [comment]
PR#141 resolving this issue is merged
