### ISSUE TITLE
Test Case: Verify Basic Clinical Trial Search functionality

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform-qa#92]
# Content Types Covered:
https://www.cancer.gov/about-cancer/treatment/clinical-trials/search

# Test scenarios:
- [x] 1. Verify that when user inputs Cancer Type, Age, ZipCode and clicks Find Trials button, correct results are displayed 
- [x] 2. Verify that when user inputs Cancer Type and clicks Find Trials button, correct results are displayed 
- [x] 3. Verify that when user inputs Cancer Type and Age and clicks Find Trials button, correct results are displayed 
- [x] 4. Verify that when user inputs Cancer Type and ZipCode and clicks Find Trials button, correct results are displayed 
- [x] 5. Verify that when user does not any search criteria and clicks Find Trials button, all results are displayed.
- [x] 6. Verify that when user inputs Age and clicks Find Trials button, correct results are displayed.
- [x] 7. Verify that when user inputs ZipCode and clicks Find Trials button, correct results are displayed.
- [x] 8. Verify that when user inputs Age which is < 1 or > 120 and clicks Find Trials button, following error message is displayed: "Please enter a number between 1 and 120."
~~9. Verify that when user navigates away from the empty Age field and clicks Find Trials button, following error message is displayed: "Please enter a number between 1 and 120."~~
- [x] 10 . Verify that when user inputs ZipCode as '99999' and '00000' and clicks Find Trials button, following error message is displayed: "Sorry, you seem to have entered invalid criteria. Please check the following, and try your search again:
Zip Code
For assistance, please contact the NCI Contact Center. You can chat online or call 1-800-4-CANCER (1-800-422-6237)."
- [x] 11. Verify that when user inputs ZipCode as 'abcd' and clicks Find Trials button, following error message is displayed: "Please enter a valid 5 digit ZIP code."
~~12. Verify that when user navigates away from the empty ZipCode field and clicks Find Trials button, following error message is displayed:  "Please enter a valid 5 digit ZIP code."~~

Depends on Issue #<number>

**Comment by SupriyaSaxena0605** [comment]
Assigning to Victoria for test case review

**Comment by VictoriaSunNIH** [comment]
@SupriyaSaxena0605  - this looks mostly correct, but i wanted to clarify that as soon as you navigate away from the age or zipcode, and have not entered correct parameters, the error message should appear (and not on submit).  For automation purposes, using on submit works, but for manual testing, the errors should appear as soon as you navigate away from that field.

For step 9 - the specific error text to appear is documented here: https://github.com/NCIOCPL/cgov-digital-platform/issues/2386

**Comment by blairlearn** [comment]
@VictoriaSunNIH  and @SupriyaSaxena0605 - the test should navigate away from the field instead of submitting for automation purposes as well.  (That's really just as simple as putting focus on another field.)

**Comment by SupriyaSaxena0605** [comment]
Thanks @blairlearn and @VictoriaSunNIH Added the tests for both Age and Zipcode.

**Comment by kate-mashkina** [comment]
items 9 and 12 are wrong scenarios due to Search is being allowed with empty ZipCode and Age fields - empty field is not an incorrect parameter.

**Comment by kate-mashkina** [comment]
PR #171  closed this issue
