### ISSUE TITLE
Test Case:  Verify Clinical Trial Search Results page

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform-qa#93]
## Content Types Covered:
https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r

### Test Scenarios:
- [x] 1. Verify title of the Search Results page is "Clinical Trials Search Results"
- [x] 2. Verify that a list of clinical trials is displayed when search criteria gives results.
- [x] 3. Verify that the Results count header text is correctly displayed on the page.
- [x] 4.Verify that the 'Show  Search Criteria' drop-down is displayed if at least one search parameter has been entered.
- [x] 5.Verify that the text "Show  Search Criteria" appears in the drop-down box if at least one search parameter has been entered.
- [x] 6.Verify that the link 'Start Over' appears in the Search Results page.
- [x] 7.Verify that the user is redirected to https://www.cancer.gov/about-cancer/treatment/clinical-trials/search if the user is coming to Search Results page from Basic CTS Form and clicking the 'Start Over' link  on the Search Results page.
- [x] 8.Verify that the user is  redirected to https://www.cancer.gov/about-cancer/treatment/clinical-trials/advanced-search if the user is coming to Search Results page from Basic CTS Form and 
clicking the 'Modify Search Criteria'' link  on the Search Results page.
- [x] 10.Verify that the user is redirected to https://www.cancer.gov/about-cancer/treatment/clinical-trials/advanced-search if the user is coming to Search Results page from Advanced  CTS Form and clicking the 'Start Over' link  on the Search Results page.
- [x] 11.Verify that the user is redirected to https://www.cancer.gov/about-cancer/treatment/clinical-trials/advanced-search if the user is coming to Search Results page from Advanced  CTS Form.
- [x] 12. Verify that the 'Select all on page' checkbox is displayed at the top and bottom of the list of trials.
- [x] 13. Verify that the checkboxes are displayed with every clinical trial displayed.
- [x] 14. Verify that the pagination is displayed on the top and bottom of the list of trials.
- [x] 15. Verify that 'Print Selected' button is displayed on the top and bottom of the list of trials.
- [x] 16.Verify that the text "No clinical trials matched your search." appears for the Search Results page with no results.
- [x] 17.Verify that the text "For assistance, please contact the NCI Contact Center. You can chat online or call 1-800-4-CANCER (1-800-422-6237)." appears in the Search Results page with no results.
- [x] 18.Verify that each page displays 10 trials
-[ ] 19. Verify that the checkbox Select all on page appears twice on the Search Results page.
-[ ] 20. Verify that the Print Selected button appears twice on the Search results page.
-[ ] 21.  Verify that the pager appears twice on the Search results page.
Negative Test:
- [x] 1.Verify that the Search Criteria drop-down is NOT displayed on the Search Results page when no parameter has been entered.

Depends on Issue [[#2392]](https://github.com/NCIOCPL/cgov-digital-platform/issues/2392)
Related Tests [#101] [#100] [#99]

**Comment by SupriyaSaxena0605** [comment]
Assigning to Victoria for test case review

**Comment by VictoriaSunNIH** [comment]
@SupriyaSaxena0605: For step 4 - search criteria only appears if user has entered any criteria in the 3 input boxes.  If they haven't, there is no search criteria accordion, but an "all results" should display in its place.

**Comment by SupriyaSaxena0605** [comment]
This will be taken care by the testdata for such scenarios

**Comment by kate-mashkina** [comment]
PR is merged
