### ISSUE TITLE
Test Case: Verify Advanced Clinical Trial Search Form

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform-qa#94]
# Pre-requisites
* pre-condition

# Content Types Covered:
https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/advanced

# Test scenarios:
- [ ] 1.Verify the title "Find NCI-Supported Clinical Trials" exists on the page
- [ ] 2.Verify the title text appears as "Find NCI-Supported Clinical Trials"
- [ ] 3.Verify that the Intro text appears on the page.
- [ ] 4.Verify that the Intro-text appears correctly as:
"NCI-supported clinical trials are those sponsored or otherwise financially supported by NCI. See our guide, Steps to Find a Clinical Trial, to learn about options for finding trials not included in NCI's collection."
- [ ] 5.Verify that the text "NCI-supported clinical trials..." in the Intro text is a link and it redirects to /Common/PopUps/popDefinition.aspx
id=CDR0000776051&amp;version=Patient&amp;language=English
- [ ] 6. Verify that the text "Steps to Find a Clinical Trial" is a link and it redirects to https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/trial-guide
- [ ] 7. Verify that the Search tip is correctly displayed with icon, 'advanced search' link and text as below:
"All fields are optional. Skip any items that are unknown or not applicable or try our basic search."
- [ ] 8.Verify that the Cancer Type/ Condition input box is displayed.
- [ ] 9.Verify that the title 'Cancer Type/ Condition' is displayed for Cancer Type/ Condition input box
- [ ] 10.Verify that the Cancer Type/ Condition input box displays help icon and links to 
https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/help#cancertype
- [ ] 11.Verify that the text "Select a cancer type/condition, then include subtypes, stages or other attributes, if applicable." is displayed in the Cancer Type/Condition input box.
- [ ] 12.Verify that the label "Primary Cancer Type/Condition" appears in the Cancer Type/ Condition input box.
- [ ] 13.Verify that the input box 'Primary Cancer Type/Condition' appears in the Cancer Type/ Condition input box.
- [ ] 14.Verify that the placeholder text "All" appears in the Primary Cancer Type/Condition input box.
- [x] 15.Verify that the 'Age' Section is displayed.
- [x] 16.Verify that the help link in the Age Section 'Age' links to https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/help#age
- [x] 17. Verify the title of the Age section.
- [x] 17.Verify that the helper text "Enter the age of the participant." appears for the 'Age' input box.
- [x] 18.Verify that the 'Keywords/Phrases' section appears on the Advanced Search page
- [x] 19. Verify the title of the Keywords/Phrases section.
- [x] 19.Verify that the placeholder text "Examples: PSA, 'Paget disease" appears in the 'Keywords/Phrases' input box.
- [x] 20.Verify that the 'Keywords/Phrases' help icon links to https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/help#keywords
- [x] 21.Verify that the help text "Search by word or phrase (use quotation marks with phrases)." appears for the 'Keywords/Phrases' section.
- [ ] 22.Verify that the 'Location' input box is displayed correctly.
- [ ] 23. Verify that the title "Location" is displayed for'Location' input box.
- [ ] 24.Verify that the 'Location'  input box displays help icon and links to  https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/help#location
- [ ] 25.Verify that the helper text "Search for trials near a specific zip code; or in a country, state and city; or at a particular institution. The default selection will search for trials in all available locations. You may choose to limit results to Veterans Affairs facilities." appears in the 'Location' input box.
- [ ] 26.Verify that the toggle for 'Limit results to Veterans Affairs facilities' appears in the 'Location' input box
- [ ] 27.Verify that the text "Limit results to Veterans Affairs facilities" appears in the 'Location' input box.
- [ ] 28.Verify that the following radio buttons appear in the 'Location' input box when the toggle is switched to "No":
Search All Locations
ZIP Code
Country, State, City
Hospitals/Institutions
At NIH (only show trials at the NIH Clinical Center in Bethesda, MD)

- [ ] 29.Verify that the radio button 'Search All Locations' is selected by default
- [ ] 30.Verify that the 'Trial Type' section is displayed.
- [ ] 37.Verify that the checkbox "All" is selected by default for the 'Trial Type'  input box.
- [ ] 38.Verify that the input box 'Drug/Treatment' is displayed.
- [ ] 39.Verify that the title 'Drug/Treatment' appears correctly.
- [ ] 40.Verify that the 'Drug/Treatment' input box displays the help icon and links to  https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/help#drugtreatment
- [ ] 41.Verify that the text "Search for a specific drug or intervention." appears correctly in the 'Drug/Treatment' input box.
- [ ] 42.Verify that the label 'Drug/Drug Family' appears for the first input box in the 'Drug/Treatment' input box.
- [ ] 43.Verify that the placeholder text "Start typing to select drugs and/or drug families" appears in the input box 'Drug/Drug Family'.
- [ ] 44.Verify that the helper text 'You can use the drug's generic or brand name. More than one selection may be made.' appears below the input box 'Drug/Drug Family'.
- [ ] 45.Verify that the label 'Other Treatments' displayed for the second input box in the 'Drug/Treatment' input box.
- [ ] 46.Verify that the placeholder text "Start typing to select other treatments" displayed in the input box 'Other Treatments'.
- [ ] 47.Verify that the helper text 'More than one selection may be made..' appears below the input box 'Other Treatments'.
- [x] 48.Verify that the'Trial Phase' section is displayed. 
- [x] 53. Verify that the check box "All" is selected by default for the 'Trial Phase' section. 
- [x] 54.Verify that the 'Trial ID' input box is displayed.
- [x] 55.Verify that the title 'Trial ID' is displayed correctly in the 
- [x] 56. Verify that the 'Trial ID' input box displays the help icon and links to  https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/help#trialid
- [x] 57.Verify that the helper text "Separate multiple IDs with commas or semicolons." appears for the 'Trial ID' input box.
- [x] 58.Verify that the 'Trial Investigators ' section is displayed.
- [x] 59.Verify that the title 'Trial Investigators' is displayed correctly.
- [x] 60. Verify that the 'Trial Investigators' input box displays the help icon and links to  https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/help#trialinvestigators
- [x] 61.Verify that the placeholder text "Investigator name" appears in the 'Trial Investigators' input box.
- [x] 62.Verify that the helper text "Search by trial investigator." appears in the 'Trial Investigators' input box.
- [x] 63.Verify that the 'Lead Organization' section is displayed.
- [x] 64.Verify that the title "Lead Organization " is displayed correctly 'Lead Organization'  input box.
- [x] 65..Verify that the 'Lead Organization'  help link  links to  https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/help#leadorganization
- [x] 66.Verify that the placeholder text "Organization name" appears in the  'Lead Organization' input box.
- [x] 67.Verify that the helper text "Search by lead organization." appears in the  'Lead Organization' input box.
- [x] 68. Verify that on entering invalid entries to Lead Organization input box, the error message "No results found" is displayed in place of helper text.

- [ ] 68.Verify that the sticky block for 'Find Trials' appear and disappear then scrolled to the button location.
- [ ] 69.Verify that the sticky block has the 'Find Trials' button.
- [ ] 70.Verify that the sticky block has 'Clear Form' button.

**Comment by alinai** [comment]
Updated Step#17 and removed Step#71 per review from @VictoriaSunNIH .

**Comment by KateMashkinaNIH** [comment]
done here https://github.com/NCIOCPL/clinical-trials-search-app/tree/develop/cypress/integration
