### ISSUE TITLE
Test Case: Verify Advanced Clinical Trial Search functionality

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform-qa#95]
# Content Types Covered:
https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/advanced

# Steps:
- [ ] 1.Verify that when user inputs Primary Cancer Type/Condition and clicks Find Trials button, correct results are displayed.
- [ ] 2. Verify when user clicks in the Primary Cancer Type/Condition input box, a box appears with the placeholder text "Start typing to narrow options below".
- [ ] 2.Verify that when user inputs Primary Cancer Type/Condition the following input boxes are displayed:
Subtype
Stage 
Side Effects/Biomarkers/Participant Attributes input boxes displays.
- [ ] 3.Verify that the label 'Subtype' appears for the Subtype input box.
- [ ]  4.Verify that the placeholder text 'Start typing to select a subtype' appears for the Subtype input box.
- [ ] 5.Verify that the helper text "More than one selection may be made." appears for the Subtype input box.
- [ ] 6.Verify that when user inputs Primary Cancer Type/Condition and inputs Subtype and clicks Find Trials button, correct results are displayed.
- [ ] 7.Verify that the label 'Stage' appears for the Stage input box.
- [ ] 8.Verify that the placeholder text "Start typing to select a stage" appears for the Stage input box.
- [ ] 9. Verify that the  helper text "More than one selection may be made." appears for the Subtype input box.
- [ ] 10.Verify that when user inputs Primary Cancer Type/Condition and inputs Stage and clicks Find Trials button, correct results are displayed.
- [ ] 11.Verify that the label 'Side Effects/Biomarkers/Participant Attributes' appears for the Side Effects/Biomarkers/Participant Attributes input box.
- [ ] 12.Verify that the placeholder text 'Start typing to select a subtype' appears for the Side Effects/Biomarkers/Participant Attributes input box.
- [ ] 13.Verify that the helper text "More than one selection may be made." appears for the Side Effects/Biomarkers/Participant Attributes input box.
- [ ] 14.Verify that when user inputs Primary Cancer Type/Condition and inputs Side Effects/Biomarkers/Participant Attributes and clicks Find Trials button, correct results are displayed.
- [ ] 15.Verify that when the user inputs Primary Cancer Type/Condition, Subtype, Stage, Side Effects/Biomarkers/Participant Attributes and clicks Find Trials button, correct results are displayed.
- [ ] 16.Verify that when the user inputs Primary Cancer Type/Condition, Subtype and Side Effects/Biomarkers/Participant Attributes and clicks Find Trials button, correct results are displayed.
- [ ] 17. Verify that when the user inputs Primary Cancer Type/Condition, Stage and Side Effects/Biomarkers/Participant Attributes and clicks Find Trials button, correct results are displayed.
- [ ] 18.Verify that when user does not enter any search criteria and clicks Find Trials button, all results are displayed.
- [X] 19.Verify that when user inputs Age between 1 and 120 and clicks Find Trials button, correct results are displayed.
- [X] 20.Verify that when user inputs Age which is < 1 or > 120 and clicks Find Trials button, following error message is displayed: "Please enter a number between 1 and 120."
- [X] 21.Verify when the user enters "1234" in the Age input box and clicks Find Trials button,  the following error message is displayed "Please enter a number between 1 and 120."
- [X] 22.Verify when the user enters "abcd" in the Age input box and clicks Find Trials button,  the following error message is displayed "Please enter a number between 1 and 120."
- [X] 23. Verify when user enters Age between 1 and 120 and hits enter  correct results are displayed.
- [x] 24.Verify that when user inputs Keywords/Phrases such as "lymphoma" in the  Keywords/Phrases input field and clicks Find Trials button, correct results are displayed.
- [x] 25.Verify that when user inputs Keywords/Phrases such as "Hodgkin Lymphoma" (the term in double quotes) in the  Keywords/Phrases input field and clicks Find Trials button, correct results are displayed.
- [x]  26. Verify that when user inputs Keywords/Phrases such as "lymphoma" in the  Keywords/Phrases input field and and hits enter, correct results are displayed.
- [x] 26.Verify that on switching the toggle to "Yes" for the Location input box, the following radio buttons appear:
Search All Locations
ZIP Code
Country, State, City
- [x] 27.Verify that on selecting the ZIP Code radio button, the following input box and the drop-down appears:
U.S. ZIP Code (input box)
Radius (drop-down)
- [ ] 28.Verify that the label 'U.S. ZIP Code' appears for the 'U.S. ZIP Code' input box, the label 'Radius' appears for the 'Radius' drop-down and the value '100 miles' appears as the default value in the 'Radius' drop-down
- [ ] 29.Verify that when user inputs U.S. ZIP Code as '99999' and '00000' and clicks Find Trials button, following error message is displayed: "Sorry, you seem to have entered invalid criteria. Please check the following, and try your search again:
. Zip Code
For assistance, please contact the NCI Contact Center. You can chat online or call 1-800-4-CANCER (1-800-422-6237)."
- [ ] 30.Verify when the user enters "abcd" in the U.S. ZIP Code input box and clicks Find Trials button,  the following error message is displayed "Please enter a valid 5 digit ZIP code.."
- [ ] 31.Verify when the user enters "1234" in the U.S. ZIP Code input box and clicks Find Trials button,  the following error message is displayed "Please enter a valid 5 digit ZIP code.."
- [ ] 32.Verify that the user is able to select the radius from the 'Radius' drop-down.
- [ ] 33. Verify that on selecting 'Country, State, City' radio button, the following are displayed:
Country - which should appear as drop-down
State-which should appear as a multi-select box
City-which should display as input box
- [ ] 34.Verify that in the Country drop-down, "United States" appears by default
- [ ] 35.Verify that the user is able to select values from the Country drop-down.
- [ ] 36.Verify that the user is able to enter multiple state in the 'State' multi-select input box
- [ ] 37.Verify that when the user types a letter (for example 'p') the State starting with the letter 'P' shows up in the auto-suggest list
- [ ] 38. Verify that the helper text "More than one selection may be made." appears for the 'State' multi-select field
- [ ] 39. Verify that the user is able to enter the name of a city in the 'City' input box.
- [ ] 40.Verify that on selecting Hospitals/Institutions radio button an auto complete input box is displayed
- [ ] 41.Verify that the placeholder text "Start typing to select a hospital or institution" appears in the 'Hospital/Institutions' input box
- [ ] 42.Verify that the text "Please enter 3 or more characters" appears on clicking the 'Hospitals/Institutions' autocomplete input box
- [ ] 43.Verify that the user is able to select the radio button 'At NIH (only show trials at the NIH Clinical Center in Bethesda, MD)
- [ ] 44.When the user switches the healthy volunteer toggle first to 'YES' and then  to "NO" in the Trial Type section and clicks Find Trials button, we will verify that system goes back to displaying default (not filtered by healthy volunteers) results after search submitted
- [ ] 44.Verify when the toggle is switched to 'Yes' and Find  Find Trials button, is clicked correct results are displayed.
- [ ] 45. Verify that when 'All' checkbox is selected and user clicks Find Trials button, all results are displayed.
- [ ] 45. Verify that when any one checkbox is selected for the Trial Type ,  'All' checkbox gets deselected. 
- [ ] 45. Verify that when none of the checkbox is selected for the Trial Type,'All' checkbox gets selected.
- [ ] 46. Verify that when the user selects any one checkbox (e.g. Treatment) for the Trial Type and clicks Find Trials button, correct results are displayed.
- [ ] 46. Verify that when the user selects more than one checkbox (e.g. Treatment and Prevention) for the Trial Type and clicks Find Trials 
- [ ] 44.Verify that when any one checkbox is selected for the Trial Type ,  'All' checkbox gets deselected.
- [ ] 45.Verify that when none of the checkbox is selected for the Trial Type,'All' checkbox gets selected.
- [ ] 46.Verify that when user selects 'Treatment' checkbox and clicks Find Trials button, correct results are displayed.
- [ ] 47.Verify that when user selects 'Treatment' checkbox and clicks Find Trials button, correct results are displayed.
- [ ] 48.Verify that when user selects 'Treatment', 'Supportive Care', 'Diagnostic','Basic Science', 'Prevention','Health Service Research', 'Screening' and 'Screening' checkbox and clicks Find Trials button, correct results are displayed.
- [ ] 49.Verify that the helper text 'Please enter 3 or more characters' appears on clicking the 'Drug/Drug Family' input box.
- [ ] 50. Verify that when user selects an option from the autocomplete for the 'Drug/Drug Family' and clicks Find Trials button, correct results are displayed.
- [ ] 51.Verify that when user selects multiple options from the 'Drug/Drug Family' and clicks Find Trials button, correct results are displayed.
- [ ] 52.Verify that the helper text 'Please enter 3 or more characters' appears on clicking the the 'Other Treatments' input box within the Drug/Treatment input box.
- [ ] 53. Verify that when user selects an option from the autocomplete for the  'Other Treatments' input box and clicks Find Trials button, correct results are displayed.
- [ ] 54.Verify that when user selects multiple options from the autocomplete for the 'Drug/Drug Family' and clicks Find Trials button, correct results are displayed.
- [x] 55.Verify that when any one checkbox is selected for the Trial Phase , 'All' checkbox gets deselected. 
 - [x] 56.Verify that when none of the checkbox is selected for the Trial Phase,'All' checkbox gets selected. 
 - [x] 56. Verify when the user selects the 'All' check box for the Trial Phase and clicks Find Trials button, correct results are displayed. 
 - [x] 57.Verify that when the user selects one of the checkbox (e.g. Phase I) for the Trial Phase and clicks Find Trials button, correct results are displayed. 
- [x] 58.Verify that when the user selects more than one checkbox check (e.g. 'Phase I' and 'Phase II' checkbox) in the Trial Phase section and clicks Find Trials button, correct results are displayed. 
- [x] 59.Verify that when user enters values separated by semi-colons(e.g. 14269;A011401;A011502)  in the Trial ID field and clicks Find Trials button, correct results are displayed.
- [x] 60.Verify that when user enters values separated by commas (e.g. 14269;A011401;A011502)  in the Trial ID field and clicks Find Trials button, correct results are displayed.
- [x] 61.Verify that the helper text 'Please enter 3 or more characters' appears on clicking the 'Trial Investigators' input box.
- [x] 62.Verify that when user selects an option from the autocomplete for the  'Trial Investigators' input box and clicks Find Trials button, correct results are displayed.
- [x] 63. Verify that when user selects an option from the autocomplete by selecting 'Enter' for the  'Trial Investigators' input box and hits 'Enter', correct results are displayed.
- [x] 63.Verify that the helper text 'Please enter 3 or more characters' appears on clicking the 'Lead Organization' input box.
- [x] 64.Verify that when user selects an option from the autocomplete for the 'Lead Organization' input box and clicks Find Trials button, correct results are displayed.
- [x] 65. Verify that when user selects an option from the autocomplete for the 'Lead Organization' 
input box and hits "Enter", correct results are displayed.
- [ ] 65.Verify that the 'Find Trials' button submits the form and the user is directed to the CTS search results page.
- [ ] 66.Verify that the 'Clear Form' button on the sticky block clears the form.

**Comment by KateMashkinaNIH** [comment]
done as part of app acceptance tests https://github.com/NCIOCPL/clinical-trials-search-app/tree/develop/cypress/integration
