### ISSUE TITLE
Test Case: Verify Cross-Cutting Elements - API Reference Block

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform-qa#99]
# Content Types Covered:
https://www.cancer.gov/about-cancer/treatment/clinical-trials/advanced-search

# Steps:
1.Verify that the Clinical Trials API box display correctly on the form.
2.Verify that the title "The Clinical Trials API: Use our data to power your own clinical trial search" appears on the Clinical Trials API box.
3.Verify that the 'Gear' icon is displayed on the API box.
4.Verify that the text "An application programming interface (API) helps translate large amounts of data in meaningful ways. NCI’s clinical trials search data is now powered by an API, allowing programmers to build applications " appears on the API box.
5.Verify that the text "using this open data." appears as a link and it redirects to https://www.cancer.gov/syndication/api

Depends on Issue #<number>

**Comment by kate-mashkina** [comment]
API reference blog is the content. Will not be included into the CTS automation set of tests
